// Maximum Value generated by using two variable 


#include<stdio.h>

int main(){
    int a,b,max;

    printf("Enter the value of a,b : ");
    scanf("%d%d",&a,&b);

    max = (a>b)?printf("A is max"):printf("B is max");
    return 0;
}